---
# When force_package_sync is enabled, any packages not in the package list
# below will be purged from the system. Packages required to keep the system
# running are either explictly listed below or protected from automatic
# removal
- name: upgrade packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: "{{ force_package_sync }}"

# mark all installed packages as "automatically" installed. This alone doesn't
# change the state of any packages on the system. It will allow them to be
# removed when the "autoremove" set runs, unless they get re-marked as
# "manually" installed
- name: unmark all packages
  ansible.builtin.shell: apt list --installed | awk -F/ '{print $1}' | xargs apt-mark auto
  when: force_package_sync

- name: install packages
  ansible.builtin.apt:
    name:
      # kernel requirements
      - device-tree-compiler
      - flash-kernel
      - libubootenv-tool
      - linux-firmware-raspi2
      - linux-raspi
      - u-boot-rpi
      - u-boot-tools
      # userland rpi tools
      - rpi-eeprom
      # ansible requirements
      - lsb-release
      - openssh-server
      - python3
      - python3-apt
      - sudo
      # ceph requirements
      - lvm2
      # container runtimes
      - containerd
      - systemd-container
      - podman
      - catatonit
      # kubernetes
      - conntrack
      - ipset
      - keepalived
      - nginx
      - socat
      # common packages
      - bwm-ng
      - curl
      - htop
      - iproute2
      - iputils-ping
      - less
      - mlocate
      - mosh
      - parted
      - sysstat
      - tmux
      - vim
    install_recommends: no

# Remove all pakages that are not protected and not required by the deps set
# in the previous task
- name: autoremove packages
  ansible.builtin.apt:
    autoremove: yes
    purge: yes
  when: force_package_sync

- name: autoclean packages
  ansible.builtin.apt:
    autoclean: yes
