---
- name: setup hosts
  hosts: all
  vars:
    apt_proxy_server: http://10.0.42.254:3142
    ntp_server: 10.0.42.254
    force_package_sync: false
  remote_user: sam
  become: yes
  tasks:
    - name: setup internal resources
      include_tasks: resources.yml
      tags: resources

    - name: update packages
      include_tasks: apt.yml
      tags: apt

    - name: update firmware
      include_tasks: firmware.yml
      tags: firmware
