---
- name: setup apt proxy
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/proxy
    content: |
      Acquire::http { Proxy "{{ apt_proxy_server }}"; }

- name: configure systemd-timesyncd
  community.general.ini_file:
    path: /etc/systemd/timesyncd.conf
    section: Time
    option: NTP
    value: "{{ ntp_server }}"
  register: timesyncd_conf

- name: restart systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
  when: timesyncd_conf.changed

- name: start and enable systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: started
    enabled: yes
