---
- name: setup config directory
  file:
    state: directory
    path: "{{ etcd_config_dir }}"

- name: setup data directory
  file:
    state: directory
    path: "{{ etcd_data_dir }}"
    mode: '0700'

- name: install CA cert
  copy:
    src: "{{ certificates_dir }}/{{ item }}"
    dest: "{{ etcd_config_dir }}/{{ item }}"
  loop:
    - ca.pem
    - etcd-peer-ca.pem
  notify: restart etcd

- name: install etcd server certs
  copy:
    src: "{{ certificates_dir }}/{{ ansible_fqdn }}/{{ item }}"
    dest: "{{ etcd_config_dir }}/{{ item }}"
  loop:
    - cert.pem
    - cert-key.pem
    - etcd-peer-cert.pem
    - etcd-peer-cert-key.pem
  notify: restart etcd

- name: template etcd systemd service
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  notify:
    - systemctl daemon-reload
    - restart etcd
